### ISSUE TITLE
Integrations fails with latest Home Assistant Update

### ISSUE THREAD

**Issue by nuttersrest** [LightwaveSmartHome/homeassistant-lightwave-smart#32]
With the release of the latest HomeAssistant update, the latest GA version of Lightwave 3.5.31 no longer loads.
Beta versions 3.5.32 to 3.5.34 do load but is difficult to use as everything is named and renamed switch on restart.

My versions
Installation method: Home Assistant OS
Core 2025.6.0b5
Supervisor 2025.05.5
Operating System 15.2
Frontend 20250531.0

The issue started at 2025.6
Is there any way to recover from this, have tried completely removing and re-adding but the only way to run the integration is to load the beta version, which has its own challenges.

From the debug log I can see the following error. Details obscured.

`2025-05-28 23:27:48.275 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@yyyyyy.com for lightwave_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/__init__.py", line 142, in async_setup_entry
    forward_setup = hass.config_entries.async_forward_entry_setup
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-05-28 23:27:48.677 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@yyyyyy.com (GB) for dyson_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_cloud/__init__.py", line 63, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-05-28 23:27:49.535 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=21=192*eu=west=1*compute*internal=859","transactionId":21611085,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1748471269476,"featureId":"5f9973daa74d380d72e42dd7-18-3157349+1","deviceId":2,"type":"power","channel":0,"writable":false,"stateless":false,"virtual":false,"value":1074,"status":"ok","productCode":"LW600","manufacturerCode":"LightwaveRF","source":"rfHeat"},"success":true,"itemId":1}]}', extra='')
2025-05-28 23:27:49.536 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: handling notification event of class: feature 
2025-05-28 23:27:49.549 DEBUG (MainThread) [lightwave_smart.lightwave_smart] _feature_event_handler: Event received - items: 1 
2025-05-28 23:27:49.567 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Starting consumer handler
2025-05-28 23:27:49.567 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=21=192*eu=west=1*compute*internal=859","transactionId":21611086,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1748471269476,"featureId":"5f9973daa74d380d72e42dd7-19-3157349+1","deviceId":2,"type":"energy","channel":0,"writable":false,"stateless":false,"virtual":false,"value":15269831,"status":"ok","productCode":"LW600","manufacturerCode":"LightwaveRF","source":"rfHeat"},"success":true,"itemId":2}]}', extra='')
2025-05-28 23:27:49.567 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: handling notification event of class: feature 
2025-05-28 23:27:49.573 DEBUG (MainThread) [lightwave_smart.lightwave_smart] _feature_event_handler: Event received - items: 1 
2025-05-28 23:27:49.579 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Starting consumer handler
2025-05-28 23:27:49.580 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=21=192*eu=west=1*compute*internal=859","transactionId":21611087,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1748471269477,"featureId":"5f9973daa74d380d72e42dd7-20-3157349+1","deviceId":2,"type":"rssi","channel":0,"writable":false,"stateless":false,"virtual":false,"value":-80,"status":"ok","productCode":"LW600","manufacturerCode":"LightwaveRF","source":"rfHeat"},"success":true,"itemId":3}]}', extra='')`

**Comment by Nbuckton** [comment]
I appear to be having the same issue with 2025.06.0 which I updated today.
It seems to have removed all entities.
" Needs attention -  Failed to set up:  - check logs "
Hope this helps

Installation method Home Assistant OS
Core 2025.6.0
Supervisor 2025.05.3
Operating System 15.2
Frontend 20250531.2

2025-06-12 14:22:10.381 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Response for transaction 5 - feature - read - 0 
2025-06-12 14:22:10.381 DEBUG (MainThread) [lightwave_smart.lightwave_smart] consumer_handler: Starting consumer handler
2025-06-12 14:22:10.382 DEBUG (MainThread) [lightwave_smart.lightwave_smart] async_sendmessage: Response received for: 5 
2025-06-12 14:22:10.383 DEBUG (MainThread) [custom_components.lightwave_smart] Identifier found in Home Assistant device registry 628914dbb2e7c40b90507861-628914dbb2e7c40b9050786a 
2025-06-12 14:22:10.383 DEBUG (MainThread) [custom_components.lightwave_smart] Identifier exists in Lightwave config
2025-06-12 14:22:10.383 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry **myemaildetails.com** for lightwave_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/__init__.py", line 142, in async_setup_entry
    forward_setup = hass.config_entries.async_forward_entry_setup
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by araines** [comment]
Looks like the issue has been fixed (for me) in `v3.5.34-beta`.  It looks like I've ended up with some duplicated devices after the version change, so I haven't fully been through it all yet to figure out what was going on and to correct things.  YMMV.

**Comment by xela1** [comment]
https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.32-Beta should work and I think is the last one before socket switch names get reverted on every restart. 

I'd suggest trying that one

@ikb42 seeing as Lightwave are now actively advertising that it integrates with HomeAssistant, do you think you/someone else could dedicate some time to improving the integration. The last couple of betas, may have implemented useful features, but they have broken things

**Comment by xela1** [comment]
> Perfect, did not think to check for a newer version 👍 34-Beta is working, although I do have a couple of duplicates too ? Will look at that later. Thanks all for your quick responses

3.5.34 has a bug where the socket switches revert to 'switch' on a restart (I don't think it affects anything else but I've not really tested it much)

**Comment by ITHungry** [comment]
Same here, too, after upgrading to 2025.6.0

My versions
Installation method: Home Assistant OS
Core: 2025.6.0
Supervisor: 2025.05.5
Operating System: 15.2
Frontend: 20250531.2

Until the issue is resolved, I will revert to the previous core version.

**Comment by ikb42** [comment]
Hello there, I have been able to replicate the switch name reverting issue - will review the code and see what's going on there.
The duplication issue, I suspect that is not a problem in the latest Beta.

**Comment by xela1** [comment]
> Hello there, I have been able to replicate the switch name reverting issue - will review the code and see what's going on there. The duplication issue, I suspect that is not a problem in the latest Beta.

Thanks for responding @ikb42 this happens on sockets (not light switches), I'll reproduce on my dev instance this evening and document

**Comment by nuttersrest** [comment]
> Hello there, I have been able to replicate the switch name reverting issue - will review the code and see what's going on there. The duplication issue, I suspect that is not a problem in the latest Beta.

Thanks @ikb42 when you are ready to test something let me know.

**Comment by xela1** [comment]
> After quite a bit of trial and error (there seems to be an issue in HA), there is a new [Beta 3.35](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.35-Beta) As always feedback and/or PRs welcome. I'd like to get this released stable.

can confirm that the socket switches are no longer reverted on reboot, will do a bit more testing and see if there are any other noticeable issues.

off-topic, would it be possible to add the firmware update status to the existing device, rather than creating a new device (even if that means we show the firmware update on multiple devices when realistically there is only one instance of the firmware)

**Comment by nuttersrest** [comment]
> After quite a bit of trial and error (there seems to be an issue in HA), there is a new [Beta 3.35](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.35-Beta) As always feedback and/or PRs welcome. I'd like to get this released stable.

Thanks @ikb42 that works a treat and switches are no longer reverting back to a name of switch.
My OCD is playing up though as it has created new devices that with the name comprising of the two sockets on the switch and only contains the firmware update. Is there no way to duplicate the firmware button  for each socket and forgo the extra device?
Though guessing that would brake some design rule somewhere, though would make sense and prevent unneeded new devices.
